### PR TITLE
Slider image fix

### LINKED ISSUE #8: Bad textures in timer/counter
The screenshots make the issue clear. This is happening in my 64-bit Linux machine. Whenever an item drop or combination is issued, the GUI uses the character tile image for the texture of anything in the counter.
shot4
shot5

### PR DESCRIPTION
**Pull request by Enet4**
Fixes #8. The image file failed to load because of case sensitivity.

Yeah, only commit bc2c93d is relevant. I tried to keep those merge commits away from the branch, but ended up adding more. I seriously ought to work my way into a sound git usage.

### CODE REVIEW

**Comment by verhoevenv** [comment]
Thing about the merge commits is that I obviously don't want them in my repository, but if I want to remove them I have to rebase or cherry-pick, thereby changing the commit hash, which I think causes even more merges for you. So it will just get worse in this work-flow.

What you usually want is to submit a pull request from the exact same commit as the one my master branch is pointing at. Most of the time, that involves some rebasing instead of merging. Don't be afraid to change your repo's history.

Anyway. Good catch on this fix, I merged it (with cherry-picking). It's rather annoying that the game just takes another texture when it can't find what it's looking for...

**Comment by Enet4** [comment]
We do have a centralized means of setting textures (in the Grim2D façade), so maybe we can write a warning from there.

**Comment by verhoevenv** [comment]
I dug a bit deeper into this.

We do write a warning to the debug log on [resource_handler.cpp L 45](https://github.com/verhoevenv/OpenNotrium/blob/e5b52e0e8ef0d6813391007e40d72e71f2c24c63/resource_handler.cpp#L145). I checked this, there's indeed a "ERROR Loading Texture!" in the log.

But we also return -1 as texture handle.

Later, in [resource_handler.cpp L 155](https://github.com/verhoevenv/OpenNotrium/blob/e5b52e0e8ef0d6813391007e40d72e71f2c24c63/resource_handler.cpp#L155) we check to see if the texture id is in bounds of  the textures vector. It turns out the test evaluates to true because the number is signed but size() returns an unsigned number, and (signed) -1 > (unsigned) 100. So the rest of the function is not executed, the last texture remains set, which pretty much always is the font texture it seems.

Visual studio outputs a warning for the signed/unsigned comparison, by the way.

I guess we should make our debugging tools a bit more useful. The log is overflowing with cool but non-relevant info, and in the code it's not clear when what things are logged. There's also a few other tools like speedup and slowdown I've seen mentioned in the code but haven't gotten working yet.

**Comment by Enet4** [comment]
I think having a new issue on making the debugging tools useful is well justified.
In the mean time, I implemented a fix to the player being able to drop 0 items, which I will upload soon.

**Pull request closed without merging**
